name: Pull Request - React Front End

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  front-end-workflow:
    name: Front End Pull Request Workflow
    uses: Peralta-CashFlow/CashFlow-WorkFlows/.github/workflows/pull-request-front-end-v1.yml@main
    permissions:
      contents: read
      pull-requests: write